name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set timestamp
      id: vars
      run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cart:${{ steps.vars.outputs.timestamp }}


    - name: push
      run: docker push devopssupanut/cart:${{ steps.vars.outputs.timestamp }}